name: JCSGuidelines
version: '1.0.0+1'
publish_to: none
environment:
  sdk: '>=3.3.1 <4.0.0'
description: 'JCS Guidelines（循環器病ガイドライン）'
dependencies:
  auto_route: ^9.3.0+1
  cloud_firestore: '^5.4.2'
  cupertino_icons: '^1.0.6'
  dio: '^5.4.0'
  easy_pdf_viewer: '^1.0.8'
  firebase_auth: '^5.3.0'
  firebase_core: '^3.5.0'
  firebase_crashlytics: '^4.1.3'
  firebase_storage: '^12.3.2'
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: '^0.14.3'
  flutter_localization: ^0.3.1
  flutter_native_splash: '^2.4.2'
  flutter_pdfview: '^1.3.4'
  flutter_quill: ^11.0.0
  flutter_riverpod: '^2.5.1'
  flutter_screenutil: '^5.9.3'
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_signin_button: '^2.0.0'
  fluttertoast: '^8.2.8'
  freezed: '^2.4.6'
  freezed_annotation: '^2.4.1'
  get_it: ^8.0.3
  google_sign_in: '^6.2.1'
  group_list_view: '^1.1.1'
  hooks_riverpod: '^2.5.1'
  import_sorter: '^4.6.0'
  index_generator: ^4.0.1
  json_annotation: '^4.9.0'
  json_serializable: '^6.7.0'
  markdown_widget: '^2.3.2+6'
  path_provider: '^2.1.2'
  pdftron_flutter: '^1.0.1-38'
  permission_handler: '^11.3.1'
  pubspec_dependency_sorter: '^1.0.5'
  rich_text_view: '^1.3.0'
  riverpod_annotation: '^2.3.5'
  searchable_listview: '^2.14.0'
  shared_preferences: '^2.2.2'
  sliding_up_panel: '^2.0.0+1'
  webview_flutter: '^4.10.0'
dev_dependencies:
  analyzer: ^7.3.0
  auto_route_generator: ^9.3.1
  build_runner: '^2.4.11'
  custom_lint_builder: ^0.7.3
  flutter_gen_runner: '^5.6.0'
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  meta: '^1.12.0'
  riverpod_generator: '^2.3.0'
  riverpod_lint: '^2.3.10'
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/json/
    - assets/txt/
    - assets/icon/icon.png

index_generator:
  exclude:
    - '**.g.dart'
  indexes:
    - path: lib

flutter_native_splash:
  image: assets/image/splash/splash.png
  color: FFFFFF
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"  # 背景色を白に
  remove_alpha_ios: true
