name: flutter_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2

  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  google_sign_in: ^6.2.1

  flutter_screenutil: ^5.9.3

  searchable_listview: ^2.14.0
  group_list_view: ^1.1.1
  sliding_up_panel: ^2.0.0+1
  markdown_widget: ^2.3.2+6
  flutter_quill: ^9.5.20
  html_editor_enhanced: ^2.6.0

  flutter_localization: ^0.2.0
  auto_route: ^8.0.0
  
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  get_it: ^7.6.7
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  index_generator: ^3.4.1

  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.3.0
  custom_lint_builder: ^0.6.4
  riverpod_lint: ^2.3.10

  meta: ^1.12.0
  analyzer: ^6.0.0
  auto_route_generator: ^8.0.0

  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  indexes:
    - path: lib



flutter_native_splash:
  image: "assets/image/splash/splash.png"
  color: "FFFFFF"
  android: true
  ios: true