// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Flutter imports:
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHprWUdaQtqQlYKFaJvjqkqNV9UJYlLVc',
    appId: '1:256963860509:web:c9fc88b777d85969028ef4',
    messagingSenderId: '256963860509',
    projectId: 'jcsguideline',
    authDomain: 'jcsguideline.firebaseapp.com',
    storageBucket: 'jcsguideline.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCcGjEWSwLxrQunJWJnc_j6YoQZ8p-nAc',
    appId: '1:256963860509:android:5251574400f5962e028ef4',
    messagingSenderId: '256963860509',
    projectId: 'jcsguideline',
    storageBucket: 'jcsguideline.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3spWmWQqBTn1c9fkstdzPEccb7aFn0Q',
    appId: '1:256963860509:ios:0b906314d7053dc6028ef4',
    messagingSenderId: '256963860509',
    projectId: 'jcsguideline',
    storageBucket: 'jcsguideline.firebasestorage.app',
    androidClientId: '256963860509-35tjd567eg3h2n6e7fmg3nvcj2c5fka9.apps.googleusercontent.com',
    iosClientId: '256963860509-s24cf0jburbdrlp384o1oslqr34mat15.apps.googleusercontent.com',
    iosBundleId: 'jp.co.miceone.jcsguidelines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3spWmWQqBTn1c9fkstdzPEccb7aFn0Q',
    appId: '1:256963860509:ios:aaa6bddc72a362d5028ef4',
    messagingSenderId: '256963860509',
    projectId: 'jcsguideline',
    storageBucket: 'jcsguideline.firebasestorage.app',
    iosClientId:
        '256963860509-ojsg6l9hkala7vrufulc505c88shlmjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHprWUdaQtqQlYKFaJvjqkqNV9UJYlLVc',
    appId: '1:256963860509:web:517b71ba0df53009028ef4',
    messagingSenderId: '256963860509',
    projectId: 'jcsguideline',
    authDomain: 'jcsguideline.firebaseapp.com',
    storageBucket: 'jcsguideline.firebasestorage.app',
  );
}