// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jori_zQrA0CYCrOYdTIygbRpvCYMcMM',
    appId: '1:541108438363:web:4cc393dedfc4904864c67e',
    messagingSenderId: '541108438363',
    projectId: 'g-one-pdf',
    authDomain: 'g-one-pdf.firebaseapp.com',
    storageBucket: 'g-one-pdf.appspot.com',
    measurementId: 'G-ZK7TDVW1J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7IRdhO9lLu7ehdROTGlSli4wFrEQ98GA',
    appId: '1:541108438363:android:23de66f441d1336364c67e',
    messagingSenderId: '541108438363',
    projectId: 'g-one-pdf',
    storageBucket: 'g-one-pdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZHtzdxPPGqFdZWrmDMj8PwhKhqmpCXuU',
    appId: '1:541108438363:ios:eb43fb8b1f13271864c67e',
    messagingSenderId: '541108438363',
    projectId: 'g-one-pdf',
    storageBucket: 'g-one-pdf.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZHtzdxPPGqFdZWrmDMj8PwhKhqmpCXuU',
    appId: '1:541108438363:ios:eb43fb8b1f13271864c67e',
    messagingSenderId: '541108438363',
    projectId: 'g-one-pdf',
    storageBucket: 'g-one-pdf.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4jori_zQrA0CYCrOYdTIygbRpvCYMcMM',
    appId: '1:541108438363:web:5c1727739376c85164c67e',
    messagingSenderId: '541108438363',
    projectId: 'g-one-pdf',
    authDomain: 'g-one-pdf.firebaseapp.com',
    storageBucket: 'g-one-pdf.appspot.com',
    measurementId: 'G-9R4MY9BRHT',
  );
}
